import type { Metadata } from "next";
import { Caveat, Geist, Geist_Mono } from "next/font/google";
import LoadingGate from "@/components/layout/LoadingGate";
import Navbar from "@/components/layout/Navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-handwritten",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased`}
      >
        <LoadingGate delayMs={3000}>
          <div className="min-h-screen bg-background text-foreground">
            <Navbar />
            <main className="mx-auto max-w-[700px] space-y-16 px-6 py-16 sm:px-8 sm:py-24">
              {children}
            </main>
          </div>
        </LoadingGate>
      </body>
    </html>
  );
}
